# Create data set of canton labels, names, and NUTS codes
cantons_lookup <- data.frame(rbind(c("AG", "Aargau", "CH033"),
                                   c("AI", "Appenzell Innerrhoden", "CH054"),
                                   c("AR", "Appenzell Ausserrhoden", "CH053"),
                                   c("BE", "Bern", "CH021"),
                                   c("BL", "Basel-Landschaft", "CH032"),
                                   c("BS", "Basel-Stadt", "CH031"),
                                   c("FR", "Freiburg", "CH022"),
                                   c("GE", "Genève", "CH013"),
                                   c("GL", "Glarus", "CH051"),
                                   c("GR", "Graubünden", "CH056"),
                                   c("JU", "Jura", "CH025"),
                                   c("LU", "Luzern", "CH061"),
                                   c("NE", "Neuchâtel", "CH024"),
                                   c("NW", "Nidwalden", "CH065"),
                                   c("OW", "Obwalden", "CH064"),
                                   c("SG", "St. Gallen", "CH055"),
                                   c("SH", "Schaffhausen", "CH052"),
                                   c("SO", "Solothurn", "CH023"),
                                   c("SZ", "Schwyz", "CH063"),
                                   c("TG", "Thurgau", "CH057"),
                                   c("TI", "Ticino", "CH070"),
                                   c("UR", "Uri", "CH062"),
                                   c("VD", "Vaud", "CH011"),
                                   c("VS", "Valais", "CH012"),
                                   c("ZG", "Zug", "CH066"),
                                   c("ZH", "Zürich", "CH040")))
# Provide useful column names
colnames(cantons_lookup) <- c("geoRegion", "geoRegion_label", "NUTS_ID")